### ISSUE TITLE
Torch Render Along with lighting

### ISSUE THREAD

**Issue by trade12** [TheCricket/ProjectX#2]
Mod Version: 0.1.1
Forge Version: 10.13.3.1408

http://puu.sh/hUL1t/2528e97ad8.jpg - Both torch types aren't rendering

https://www.dropbox.com/s/y7kd6ke303c6uo2/2015-05-21-0055-45.flv?dl=0 - rendering issue

**Comment by TheCricket** [comment]
That looks kinda cool, but will fix it tonight

**Comment by TheCricket** [comment]
And they are broken again...
